github.com:
    users:
        Harrex:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Harrex
